name: trigger blog update

on:
  issues:
    types: [opened, closed, edited, milestoned, labeled, unlabeled, reopened, demilestoned]
  issue_comment:
    types: [created]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Download Issue and Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          curl -X POST https://api.github.com/repos/King-of-Infinite-Space/King-of-Infinite-Space.github.io/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "update", "client_payload": { "event_name": "'"$GITHUB_EVENT_NAME"'" }}'
