name: trigger blog update

on:
  issues:
    types: [opened, closed, edited]
  issue_comment:
    types: [created]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: trigger update
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const rq = await github.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'main.yml'
            })
          const runs = rq.data
          // console.log(runs)
          const updateTimeStr = runs.workflow_runs[0].updated_at
          const now = new Date()
          const last = new Date(updateTimeStr)
          const td = (now - last)/60000 // in minutes
          if (td > 30) {
            await github.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: King-of-Infinite-Space.github.io,
              event_type: context.eventName
            });
            console.log('update triggered')
          }
          else {
            console.log('update NOT triggered')
          }
