name: trigger blog update

on:
  push:
    branches:
      - master
  issues:
    types: [opened, closed, edited]
  issue_comment:
    types: [created]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: check update
      id: to-update
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const rq = await github.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'main.yml'
            })
          const runs = rq.data
          // console.log(runs)
          const updateTimeStr = runs.workflow_runs[1].updated_at // 0 is the current run
          const now = new Date()
          const last = new Date(updateTimeStr)
          const td = (now - last)/60000 // in minutes
          console.log(td)
          if (td > 30) {
            /* await github.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: 'King-of-Infinite-Space.github.io',
              event_type: context.eventName
            }); */
            console.log('update triggered')
          }
          else {
            console.log('update NOT triggered')
          }
          return (td > 30)
        result-encoding: boolean
          
    - name: trigger update
      if: ${{steps.to-update.outputs.result}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          echo "${{steps.to-update.outputs.result}}"
          curl -X POST https://api.github.com/repos/King-of-Infinite-Space/King-of-Infinite-Space.github.io/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "'"$GITHUB_EVENT_NAME"'", "client_payload": { "event_name": "'"$GITHUB_EVENT_NAME"'" }}'
