name: update blog

on:
  discussion:
    types: [created, edited, deleted]
  workflow_dispatch:

jobs:
  discussion-to-md:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "~1.25"

      - uses: actions/checkout@v3
        with:
          path: "mainRepo"

      - uses: actions/checkout@v3
        with:
          repository: "king-of-infinite-space/gh-discussions-export"
          path: "toolRepo"

      - run: |
          cd mainRepo
          deno run --allow-net --allow-env --allow-read --allow-write ../toolRepo/scripts/fetchPosts.js && ../toolRepo/scripts/commit.bash

  trigger-update:
    needs: discussion-to-md
    runs-on: ubuntu-latest
    steps:
      - name: check and trigger update
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          # GITHUB_TOKEN used by default is scoped to the current repository
          script: |
            const rq = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'main.yml'
              })
            const runs = rq.data
            const updateTimeStr = runs.workflow_runs[1].updated_at // 0 is the current run
            const now = new Date()
            const last = new Date(updateTimeStr)
            const td = (now - last) / 60000
            console.log(`last updated ${td} minutes ago`)
            if (td > 30) {
              for (const targetRepo of ['King-of-Infinite-Space']){
                await github.repos.createDispatchEvent({
                  owner: context.repo.owner,
                  repo: targetRepo,
                  event_type: context.eventName
                }); 
              }
              console.log('update triggered')
            }
            else {
              console.log('update NOT triggered')
            }
